from enum import Enum


class Keys(Enum):
    Enter = 'Enter'
    Esc = 'Esc'
    BackSpace = 'BackSpace'
    Tab = 'Tab'
    Space = 'Space'
    CapsLock = 'CapsLock'
    PrintScreen = 'Print Screen'
    ScrollLock = 'ScrollLock'
    Pause = 'Pause'
    Insert = 'Insert'
    Home = 'Home'
    Pageup = 'Pageup'
    Delete = 'Delete'
    End = 'End'
    PageDown = 'PageDown'
    Right = 'Right'
    Left = 'Left'
    Down = 'Down'
    Up = 'Up'
    NumLock = 'NumLock'
    LCtrl = 'LCtrl'
    LShift = 'LShift'
    LAlt = 'LAlt'
    LWin = 'LWin'
    RCtrl = 'RCtrl'
    RShift = 'RShift'
    RAlt = 'RAlt'
    RWin = 'RWin'
    Ctrl = 'Ctrl'
    Shift = 'Shift'
    Alt = 'Alt'
    Win = 'Win'
    F1 = 'F1'
    F2 = 'F2'
    F3 = 'F3'
    F4 = 'F4'
    F5 = 'F5'
    F6 = 'F6'
    F7 = 'F7'
    F8 = 'F8'
    F9 = 'F9'
    F10 = 'F10'
    F11 = 'F11'
    F12 = 'F12'
